// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package db

import (
	"context"
	"database/sql"
)

const createLink = `-- name: CreateLink :one
INSERT INTO
    watch_links (
        token,
        enabled,
        created_at,
        expires_at,
        disabled_at,
        note
    )
VALUES
    (?, 1, ?, ?, NULL, ?)
RETURNING
    id,
    token,
    enabled,
    created_at,
    expires_at,
    disabled_at,
    note
`

type CreateLinkParams struct {
	Token     string        `json:"token"`
	CreatedAt int64         `json:"created_at"`
	ExpiresAt sql.NullInt64 `json:"expires_at"`
	Note      string        `json:"note"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (WatchLink, error) {
	row := q.db.QueryRowContext(ctx, createLink,
		arg.Token,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.Note,
	)
	var i WatchLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Enabled,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.Note,
	)
	return i, err
}

const deleteExpiredDisabledLinks = `-- name: DeleteExpiredDisabledLinks :execrows
DELETE FROM watch_links
WHERE
    enabled = 0
    AND disabled_at IS NOT NULL
    AND disabled_at < ?
`

func (q *Queries) DeleteExpiredDisabledLinks(ctx context.Context, disabledAt sql.NullInt64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredDisabledLinks, disabledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const disableLinkByID = `-- name: DisableLinkByID :execrows
UPDATE watch_links
SET
    enabled = 0,
    disabled_at = ?
WHERE
    id = ?
    AND enabled = 1
`

type DisableLinkByIDParams struct {
	DisabledAt sql.NullInt64 `json:"disabled_at"`
	ID         int64         `json:"id"`
}

func (q *Queries) DisableLinkByID(ctx context.Context, arg DisableLinkByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, disableLinkByID, arg.DisabledAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveLinkByToken = `-- name: GetActiveLinkByToken :one
SELECT
    id,
    token,
    enabled,
    created_at,
    expires_at,
    disabled_at,
    note
FROM
    watch_links
WHERE
    token = ?
    AND enabled = 1
    AND (
        expires_at IS NULL
        OR expires_at > ?
    )
LIMIT
    1
`

type GetActiveLinkByTokenParams struct {
	Token     string        `json:"token"`
	ExpiresAt sql.NullInt64 `json:"expires_at"`
}

func (q *Queries) GetActiveLinkByToken(ctx context.Context, arg GetActiveLinkByTokenParams) (WatchLink, error) {
	row := q.db.QueryRowContext(ctx, getActiveLinkByToken, arg.Token, arg.ExpiresAt)
	var i WatchLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Enabled,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.Note,
	)
	return i, err
}

const getLastActiveLink = `-- name: GetLastActiveLink :one
SELECT
    id,
    token,
    enabled,
    created_at,
    expires_at,
    disabled_at,
    note
FROM
    watch_links
WHERE
    enabled = 1
    AND (
        expires_at IS NULL
        OR expires_at > ?
    )
ORDER BY
    created_at DESC
LIMIT
    1
`

func (q *Queries) GetLastActiveLink(ctx context.Context, expiresAt sql.NullInt64) (WatchLink, error) {
	row := q.db.QueryRowContext(ctx, getLastActiveLink, expiresAt)
	var i WatchLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Enabled,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.Note,
	)
	return i, err
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT
    id,
    token,
    enabled,
    created_at,
    expires_at,
    disabled_at,
    note
FROM
    watch_links
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetLinkByID(ctx context.Context, id int64) (WatchLink, error) {
	row := q.db.QueryRowContext(ctx, getLinkByID, id)
	var i WatchLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Enabled,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.Note,
	)
	return i, err
}

const listActiveLinks = `-- name: ListActiveLinks :many
SELECT
    id,
    token,
    enabled,
    created_at,
    expires_at,
    disabled_at,
    note
FROM
    watch_links
WHERE
    enabled = 1
    AND (
        expires_at IS NULL
        OR expires_at > ?
    )
ORDER BY
    created_at DESC
`

func (q *Queries) ListActiveLinks(ctx context.Context, expiresAt sql.NullInt64) ([]WatchLink, error) {
	rows, err := q.db.QueryContext(ctx, listActiveLinks, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchLink
	for rows.Next() {
		var i WatchLink
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.Enabled,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.DisabledAt,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
