// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type WatchLink struct {
	ID         int64         `json:"id"`
	Token      string        `json:"token"`
	Enabled    int64         `json:"enabled"`
	CreatedAt  int64         `json:"created_at"`
	ExpiresAt  sql.NullInt64 `json:"expires_at"`
	DisabledAt sql.NullInt64 `json:"disabled_at"`
	Note       string        `json:"note"`
}
