name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_type != 'tag' }}

jobs:
  check:
    permissions:
      contents: read
    uses: hu553in/common-things/.github/workflows/check-go.yml@main

  docker:
    permissions:
      contents: read
    uses: hu553in/common-things/.github/workflows/check-docker.yml@main
    with:
      build: ${{ github.ref != 'refs/heads/main' }}

  publish:
    needs: [check, docker]
    if: github.ref == 'refs/heads/main'
    uses: hu553in/common-things/.github/workflows/build-publish-attest-docker.yml@main
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      image: ghcr.io/${{ github.repository }}
