name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v9

  vulncheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: golang/govulncheck-action@v1
        with:
          go-version-file: go.mod

  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
    needs: [lint, vulncheck]
    uses: hu553in/common-things/.github/workflows/build-publish-docker.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      image: ghcr.io/${{ github.repository }}
